version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document_management_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - nest_network
    command: node dist/main.js

volumes:
  postgres_data:

networks:
  nest_network:
    driver: bridge
